### ISSUE TITLE
Rename Project to CourseUp

### ISSUE THREAD

**Issue by aomi** [VikeLabs/courseup#104]
Clockwork is a named used by UVic/CAL and is listed on MyPage.
![image.png](https://images.zenhubusercontent.com/5ed9649049c5997e275f47d9/663116c3-f837-41fb-87f1-60060899e451)
It's not worth causing confusion so we need to switch the name.

- [x] Staging Deployment Project/Domain
- [x] Production Deployment Project/Domain
- [x] GitHub Repository
- [x] GitHub Team
- [x] Discord
- [x] Sentry.io
- [x] Frontend App
- [x] Backend App
- [x] Documentation
- [x] Google drive
- [x]  ZenHub
- [x] Figma

**Comment by aomi** [comment]
@keithradford Can you check the list to see if there's anything missing?

**Comment by keithradford** [comment]
Covers all the important stuff. Minor things would be the team resources like: 

- Google drive
- ZenHub
- Figma
