### ISSUE TITLE
Always selects Summer 2021 term when no term is set

### ISSUE THREAD

**Issue by zthh626** [VikeLabs/courseup#121]
https://images.zenhubusercontent.com/340229870/7074ac79-334a-4337-aa91-1285c13811d4/screen_recording_2021_05_04_at_9_19_18_am.mov

**Comment by aomi** [comment]
@zthh626 This is actually intended behaviour unless you believe there is a concern this is a problem.

**Comment by zthh626** [comment]
@aomi It seems really unintuitive to me that it works this way, but I wouldn't say its a big deal.
