### ISSUE TITLE
Design mobile views for website

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/courseup#151]
Design a series of mock-ups for the entire CourseUp page on mobile devices. 

See the [Figma](https://www.figma.com/files/team/941575101864426585/VikeLabs---CourseUp?fuid=940849410878944954) for where to create the mock-ups.

**Comment by FlyteWizard** [comment]
Hey @keithradford ! 

I am wondering if you folks have a mockup of a responsive `header/navigation`? I am open to helping make this component responsive! 

I saw this issue #65, and I can create a new issue for the `header/navigation` component specifically if needed.

**Comment by keithradford** [comment]
@FlyteWizard We do not currently, no. Although I'm not totally apposed to making some ASAP. Google analytics shows just over 50% of users are trying to access on mobile, and if we have the people willing to code it, I am all for doing this.

**Comment by FlyteWizard** [comment]
@keithradford Awesome, if you folks can make a few mockups, I can do some more contributions this weekend! 😄

**Comment by keithradford** [comment]
@FlyteWizard Here's the figma I'll be using for the mock-up: https://www.figma.com/file/Lvep4lP1867IZUiVQHUtaz/CourseUp?node-id=101%3A8662

Nothing set in stone there yet, but good to have it tied to the ticket + we can discuss it here
