### ISSUE TITLE
Fix responsiveness of landing page

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/courseup#156]
Currently when viewing the home page and default courses page, the `Created by students @ VikeLabs` text at the bottom will wrap text, which doesn't look great.

The first screenshot is how it should always look, and the ladder shows currently what happens.

![Screen Shot 2021-05-30 at 3.30.06 PM.png](https://images.zenhubusercontent.com/5f973f7c87cad5309bf82827/0d5d499a-cd26-4880-b7a4-18252c9e8111)
![Screen Shot 2021-05-30 at 3.30.19 PM.png](https://images.zenhubusercontent.com/5f973f7c87cad5309bf82827/02a4480e-027a-403b-9581-ed8915819325)

**Comment by FlyteWizard** [comment]
Hey @keithradford !

Are you specifically looking at this part of the landing page? (i.e. you aren't concerned with the header in this issue). 

If it is the landing text specifically, I would like to make a contribution by doing a PR for this issue. 😄

**Comment by keithradford** [comment]
@FlyteWizard Yeah, the specific issue mentioned is the main focus here. The responsiveness of the rest of the page will be addressed in separate issues/PRs.

Please refer to our (WIP) [contribution guidelines](https://github.com/VikeLabs/courseup/blob/45d8b668621bb455a15566d70b4f5ec6c0ae2db9/CONTRIBUTING.md) and ask any additional questions here 😎

**Comment by FlyteWizard** [comment]
@keithradford Would you folks be opposed to eliminating the `VikeLabs` image on the landing page content in favour of plain text?

Reasoning: Image's are blurry with text, and text is easier for accessibility (scaling text on page vs scaling a compressed image). 

Is there an official font for the logo?

**Comment by keithradford** [comment]
Props for bringing up accessibility, I think you raise a great point.

cc @aomi for VikeLabs branding perspective

**Comment by aomi** [comment]
From a branding perspective for the club, I feel we should try and retain that styling. However the image below should provide enough to recreate it with fonts. 

![image](https://user-images.githubusercontent.com/1757744/120876292-cb1cdd00-c564-11eb-8878-b13316948ab6.png)

**Comment by FlyteWizard** [comment]
I tried something out for the `VIKE LABS`, but not sure if this is inline with CourseUp branding. Feel free to request changes.
