### ISSUE TITLE
Compact location names on the timetable calendar and saved courses sidebar.

### ISSUE THREAD

**Issue by aomi** [VikeLabs/courseup#158]
Currently the calendar event component and saved courses display the full length location of the meeting time as shown below:
 ![image.png](https://images.zenhubusercontent.com/5ed9649049c5997e275f47d9/c734b07c-40ef-4e51-a3e1-5b18c0eaab99)

The location names on these views should be compacted into their respective short forms like so:
- Elliott Building 162 to ELL 162
- Engineering Lab Wing B215 to ELW B215

The implementation would likely involve a lookup table which contains the full length building/location name as the key to the shorthand version. For example:
```js
// lookup table
const locations = {
'Engineering Lab Wing': 'ELW' 
};

// using lookup table
const shorthand = locations['Engineering Lab Wing']
```

If a list of location / buildings cannot be found online, ping @aomi @keithradford for guidance / assistance

**Comment by keithradford** [comment]
Where on our website location is used:

- course view (i.e. https://courseup.vikelabs.ca/calendar/202105/BCMB?pid=rJMbCv6Q4)
- timetable calendar events
- timetable right sidebar

Plan:

- For the **timetable sidebar and course view**, we can keep it in long form for when the screen size is bigger. When screens get smaller, it can convert into the short form.
- For the **timetable event** it should probably always be short form
- Any case of short form should be a tool tip ([chakra docs](https://chakra-ui.com/docs/overlay/tooltip)) that shows the long form on hover

**Comment by keithradford** [comment]
Update: this is purely a frontend issue now, backend has been implemented
