### ISSUE TITLE
Link to GitHub repo from header

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/courseup#163]
Add a button (github icon button) on the far right-side of the header. Should link to the github repo!

**Comment by siddharthpk** [comment]
Hey @keithradford is this project yet open to contribution for anyone?

**Comment by keithradford** [comment]
@siddharthpk Yes, it is! We are currently in the process of fleshing out the contribution guidelines & process, so apologies if anything seems unclear ATM. 

Feel free to refer to the [README here](https://github.com/VikeLabs/courseup/blob/bb10e7dfd5b115fc8b3b65b8d927f6e5f82a8f97/README.md) which has some hopefully helpful details and ask any questions you may have in this issue.

**Comment by siddharthpk** [comment]
That's great! I'd like to work on this so I'll start with the contribution guidelines and make a PR soon.
