### ISSUE TITLE
When one course is already hidden hiding the one on the bottom hides all of the courses.

### ISSUE THREAD

**Issue by Zerva5** [VikeLabs/courseup#174]
Sorry if the title is a little confusing. Please see the images I've attached. As you can see in the second image CSC 370 is selected but is still hidden. The sections selected for CSC 320 don't matter, still the same result. Reproducible in an incognito tab on Firefox.

![Before](https://user-images.githubusercontent.com/20209896/120711507-54a0b200-c474-11eb-9424-8553a1d49043.png)
![After](https://user-images.githubusercontent.com/20209896/120711519-566a7580-c474-11eb-81a5-43719253f856.png)

**Comment by aomi** [comment]
@Zerva5 It's probably because you're on a week that where CSC 370 has ended already. Try moving back a week in the state you're in on the second photo.

**Comment by Zerva5** [comment]
I'm an idiot. Sorry I didn't even see that.
