### ISSUE TITLE
STAT 350 (and maybe others) shows as having no sections available when UVic's course lookup says otherwise.

### ISSUE THREAD

**Issue by Zerva5** [VikeLabs/courseup#175]
Please see screenshots. Was done in an incognito tab on Firefox with no other classes added to the timetable.
![CourseUp](https://user-images.githubusercontent.com/20209896/120712057-03dd8900-c475-11eb-941d-ea7bf6904579.png)

![UVic course lookup](https://user-images.githubusercontent.com/20209896/120712036-fb854e00-c474-11eb-8470-cb0de1d86a8a.png)

**Comment by aomi** [comment]
@Zerva5 Thanks for the issue report. I found the issue and should be fixed tonight hopefully.

Future tip, providing the links would be perfectly fine :+1:
