### ISSUE TITLE
Accessibility: Empty Alt Text - Landing Page

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#180]
Empty Alt Attribute:

Suggestion: Add `alt=""` to the `Image` element.

https://github.com/VikeLabs/courseup/blob/3dae7328a796fb70a9ac78551ed9e5be321c324f/src/app/landing/index.tsx#L42-L48

You can read more about empty alt attribute here: https://html.spec.whatwg.org/multipage/images.html#a-purely-decorative-image-that-doesn't-add-any-information

TLDR: When an image is purely decorative, you can add an empty alt attribute. 

This is a `good first issue` candidate.

**Comment by poly4concept** [comment]
hi @aomi and @FlyteWizard can you assign this to me. I would love to contribute

**Comment by FlyteWizard** [comment]
@poly4concept and @aomi It might be best to wait on this issue until #181 is either closed or merged.

**Comment by poly4concept** [comment]
Hi @FlyteWizard, is there any particular alt text you want me to use, should the alt text be dynamic and I should just use something related to the image

**Comment by FlyteWizard** [comment]
@poly4concept For this alt text, the image is purely decorative, and therefore `alt=""` is sufficient. It doesn't need to be dynamic as it doesn't add anything to the experience. 

Note: This issue only pertains to the landing page image mentioned in the issue description. 

Thank you for asking these types of questions 😄

**Comment by poly4concept** [comment]
Yeah I understand now, thank you @FlyteWizard for explaining
