### ISSUE TITLE
Bug: Add to Timetable + Button - Remove/Disable Button

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#185]
**Describe the bug**

The `Add to Timetable` button is present and clickable and functional even when no courses are available for this term. 

**To Reproduce**

1. Got to https://courseup.vikelabs.ca/calendar/202105/ACAN?pid=ByS23Pp7E
2. Click `Add to Timetable`
3. Go to https://courseup.vikelabs.ca/scheduler/202105
4. View courses that isn't available

**Expected behaviour**

That the buttons for adding an unavailable course is disabled or removed.

**Screenshots**

<img width="1335" alt="Capture d’écran, le 2021-06-05 à 10 56 29" src="https://user-images.githubusercontent.com/10472448/120901030-2beff800-c5ed-11eb-8997-f91031eb682a.png">

<img width="1675" alt="Capture d’écran, le 2021-06-05 à 11 00 25" src="https://user-images.githubusercontent.com/10472448/120901044-40cc8b80-c5ed-11eb-84d4-2ba2d8b4d029.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: Latest

**Additional context**

This prevents users (especially in the `Timetable` view) from being confused when a course doesn't appear after selection. 

This is still applicable even when a user doesn't filter by `courses in session`. We shouldn't expect users to use filters.

**Comment by aomi** [comment]
@shergillmanav19 This isn't a trivial fix (at least to do properly). This might need some backend changes to make it work well.

**Comment by shergillmanav19** [comment]
@aomi kk ill leave it to you then?

**Comment by shergillmanav19** [comment]
@aomi wouldn't this be automatically fixed with my latest PR because a user wont be able to access those courses if the filter is on?

**Comment by aomi** [comment]
@shergillmanav19 well the button would still work if you didn't have the filter on.
