### ISSUE TITLE
Feature: Add CRN to Timetable Course View

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#186]
Add the CRN to the `Saved Courses` view. This is one of the most useful things for students when they register for courses, as you can input all CRNs and register in one easy click, therefore having the CRNs easily visible is a must.

## Current

<img width="1673" alt="Capture d’écran, le 2021-06-05 à 11 14 10" src="https://user-images.githubusercontent.com/10472448/120901381-4f1ba700-c5ef-11eb-909a-76ead60149d3.png">

## Option 1

You folks are welcomed to provide an option that adheres to your style guide, but something similar to the following would be ideal:

<img width="1671" alt="Capture d’écran, le 2021-06-05 à 11 17 29" src="https://user-images.githubusercontent.com/10472448/120901429-b20d3e00-c5ef-11eb-86db-472f3fd869d7.png">

**Comment by aomi** [comment]
Keith is working on a "Registration View" which would show the CRNs and anything useful for registration purposes.
https://github.com/VikeLabs/courseup/issues/160
I'm going to close this in favour of the other issue for discussion etc.
