### ISSUE TITLE
Feature: Responsive Header/Navigation

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#203]
Related to #151 

Add responsive design to `Header/Navigation` component. Once responsive this component will be accessible and mobile friendly.

**Comment by FlyteWizard** [comment]
I'd be interested in taking this issue once mockups have been created 😄

**Comment by keithradford** [comment]
💪 mock-ups are still a WIP. Wouldn't mind some feedback, but will also be working with the core-team on this one so we can get try and work out the best design.
https://www.figma.com/file/Lvep4lP1867IZUiVQHUtaz/CourseUp?node-id=101%3A8662

**Comment by FlyteWizard** [comment]
Here is a few ideas for the responsiveness of the header. Let me know what you think. 😄 

<img width="932" alt="Capture d’écran, le 2021-06-25 à 19 16 44" src="https://user-images.githubusercontent.com/10472448/123499211-ec17a180-d5e9-11eb-9df9-ac1c5596348e.png">

**Comment by aomi** [comment]
I like the direction of the mobile layouts! (frame X - 14) I was thinking if it would be possible to have the "Courses" and "Timetable" button together (like the desktop view) and the same thing for the terms. I would maybe have the magnifying glass icon (search) to the right of the hamburger for the mobile, which would then open the menu and put focus to the search bar (like currently mocked up) and open the keyboard for input?

For the desktop layouts, I have mixed feelings with adding a "hamburger" menu as it adds another action needed to get to the features.

**Comment by FlyteWizard** [comment]
For the desktop layout, we don't need to do hamburger, but I still think there might be value of having the second line. This allows for a better overall responsiveness. However, if someone has a better way of doing this please let me know 😄 
Alternatively, we can have the hamburger menu open by default? but that isn't conventional, so might confuse users.

I'm hesitant to do the "together" buttons on mobile / small screens just because it might allow for more user error while tapping (as the space is smaller). But I do agree that there is a lot of buttons with the current layout in frame `X - 14`.  Having the search icon in the header is probably a very smart move, helps prompt the user, good point! 

While talking about removing extra clicks, I think it might be beneficial to looking at a bottom navigation for small screen users. This way we eliminate the need for users to continue clicking the hamburger button to perform tasks.
