### ISSUE TITLE
Look into .ICS and react-big-calendar integration

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/courseup#214]
If we want to export calendars to .ICS format it is important to scope out:

- [ ] How ICS files are structured/created
- [ ] What react-big-calendar/our events have that align with this
- [ ] What additional information needs to be included from our page for ICS

**Comment by FlyteWizard** [comment]
Hey! 

For information about .ICS files they are pretty straight forward. 
You can view some examples of what students have made here: <https://github.com/malcolmseyd/uvic-schedule-exporter> and here <https://github.com/FlyteWizard/UVicSchedule>. 

The `UVic Schedule Exporter` works best as it supports a few different edge cases.

**Comment by keithradford** [comment]
@FlyteWizard Awesome!

**Comment by aomi** [comment]
A lot of the processing is done already to put it into `react-big-calendar` so I imagine it'll be very straightforward. Mozilla also maintains https://github.com/mozilla-comm/ical.js/ which can be used if needed (but I'm guessing we won't need to)

**Comment by FlyteWizard** [comment]
@aomi If you use `UID` in the creation of the event (a specific course), you can have it `sync/update` the already uploaded .ICS. 

For example, I used the CRN, YEAR, and MONTH as my unique identifier for each event, and this allows for multiple uploads to a calendar without duplicate events. 

However, this might be difficult to present to non technical users.

**Comment by FlyteWizard** [comment]
Syncing already added courses and not allowing duplicates is easily fixed with `UID`.

The biggest problem is removing old courses.
