### ISSUE TITLE
Info button doesn't work when searching course on timetable page

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/courseup#215]
When searching for a course on [the timetable page](https://courseup.vikelabs.ca/scheduler/202109), clicking the "info" button (blue button with an `i`) does not work as expected.
It should take you to the course info page for that given course, but it currently does not.

Current info about the bug:

- The PID for the selected course is appended as a query param which is correct, however it is added to the URL with `scheduler` instead of `calendar`
- It appears to briefly redirect to the correct URL in the browser search bar but the page does not change

**Comment by syeo-1** [comment]
I'd like to try working on this issue. Is there any additional info that may have come up since the issue has opened that may be helpful for working on this?

**Comment by keithradford** [comment]
@syeo-1 Haven't had the chance to dive into it so all info provided is what we know. Let me know if you have any questions, I'd be happy to help!

**Comment by chendumpling** [comment]
<img width="494" alt="Untitled" src="https://user-images.githubusercontent.com/66714443/133002533-792e614b-c23e-4631-bcef-a72a5d8276ba.png">
Deleting this event listener in chrome devtools and then clicking the info button(s) leads to the correct URL, but the TS file linked "helper.ts:64" goes to a commented section so I'm unsure of how to proceed.
