### ISSUE TITLE
Remove dayjs library

### ISSUE THREAD

**Issue by aomi** [VikeLabs/courseup#216]
Given react-big-calendar doesn't support dayjs and we have date-fns let's remove dayjs so we have a single date utility library. 
This issue involves `npm uninstall dayjs` and replacing any usage of dayjs with date-fns.

**Comment by szeckirjr** [comment]
hey, I can try helping out with this :D

I was looking through the code and could only find dayjs being used in `src/lib/utils/terms.ts`. Can you confirm that's the only place that needs changing?

**Comment by aomi** [comment]
That should be the only thing. If you remove the package and don't replace all uses of it it'll get mad during build too :wink:
