### ISSUE TITLE
Responsiveness - Registration Page

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#222]
**Describe the bug**

The responsiveness of the registration page has a few issues with text cutoff and missing spacing border around text.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to https://courseup.vikelabs.ca/registration/202109
2. Resize browser and view issues.

**Expected behavior**

The text has adequate spacing between the sides of the browser, and the text doesn't get cutoff. 

**Screenshots**

<img width="841" alt="Capture d’écran, le 2021-06-16 à 19 38 41" src="https://user-images.githubusercontent.com/10472448/122322855-fdbac400-ceda-11eb-8388-288318b0c6c6.png">

<img width="569" alt="Capture d’écran, le 2021-06-16 à 19 38 55" src="https://user-images.githubusercontent.com/10472448/122322860-001d1e00-cedb-11eb-9370-73efa4477f57.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: Latest

**Additional context**

This shouldn't require any additional design changes.

**Comment by FlyteWizard** [comment]
Hey! I am open to contributing to this issue if possible 😄

**Comment by keithradford** [comment]
@FlyteWizard Good catch. I think it's the area between the `sm` and `base` breakpoints [here](https://github.com/VikeLabs/courseup/blob/main/src/pages/registration/containers/RegistrationContainer.tsx#L26) that is the issue. Most likely can be addressed with some sizing changes on that line.

Feel free to work on it and let me know if you have any questions 👍
