### ISSUE TITLE
Bug: Remove or Hide or Update Banner (Announcement)

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#234]
**Describe the bug**

"Hey! We're holding office hours and a backend developer workshop for CourseUp on June, 19th at 11 am PDT on the VikeLabs Discord! Click here to learn more!" Is still the announcement banner when people visit CourseUp. The banner should be updated or removed/hidden. (Probably just removed, but keep the component).

**To Reproduce**

Steps to reproduce the behaviour:

1. Visit https://courseup.vikelabs.ca
2. See the outdated announcement banner

**Expected behavior**

The announcement banner to be current.

**Screenshots**

<img width="1680" alt="Capture d’écran, le 2021-06-24 à 14 50 49" src="https://user-images.githubusercontent.com/10472448/123337218-bdbb9880-d4fb-11eb-88cb-598125aabbca.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: Latest

**Additional context**

This has potential to be a good first issue. Might be good for onboarding 😄

**Comment by keithradford** [comment]
In progress! Working on this now, adding some tips it will cycle through.
