### ISSUE TITLE
Bug: CourseUp Header Link - "Broken"

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#236]
**Describe the bug**

Clicking on the CourseUp text in upper left in the header should be a hyperlink to the homepage, but currently does nothing.

**To Reproduce**

Steps to reproduce the behaviour:

1. https://courseup.vikelabs.ca/calendar/202105 
2. Click CourseUp
3. Notice it doesn't change the URL or Page

**Expected behavior**

That by convention, CourseUp brings me to the homepage.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: Latest

**Comment by FlyteWizard** [comment]
@VikeLabs/courseup

Hey! Can I take on this issue? It seems like a straightforward fix. Are we good with it linking back to the homepage?

**Comment by keithradford** [comment]
I’m away right now so I can’t finish the PR, but Aomi is closing up #235 (I
think it’s that one) where I addressed this issue. Did it as part of the
banner refactor PR.

**Comment by aomi** [comment]
I was just rebasing to verify that ci was broken due to a old branch. Don't have any intentions to take over lol.

Perhaps we remove the updated banner info and fix logo link in a pr in the meantime?

**Comment by keithradford** [comment]
Oh I saw the commits and thought they were you
