### ISSUE TITLE
Bug: Courses scheduled to end after 8pm are not displayed correctly on calendar

### ISSUE THREAD

**Issue by CoBr8** [VikeLabs/courseup#249]
### Description:
When adding labs that extend past 8:00pm the UI will make the lab appear to end at 8:00pm instead. 

### Steps to reproduce the behaviour/bug/issue:
1. navigate to: https://courseup.vikelabs.ca/
2. select fall or winter term
3. add course with evening lab (eg. 2021-09 Phys 323, using lab B03 or Phys 229 using lab B04)
4. Open calendar
5. Scroll to bottom of calendar

### Expected:
One of the following:
1. Calendar is extended to accommodate these end times.
2. Courses ending between 8:00pm and 9:00pm are show correctly, and courses that end after 9:00pm are given a note on the calendar entry of the actual end time. 
3. Removing the time block after 7:59pm and then the same output as (2.) above except the cut-off is 8:00pm instead of 9:00pm

#### Screenshots
The courses not extending past 8:00pm

![image](https://user-images.githubusercontent.com/49500055/126845290-da8040e6-8014-45c4-a5da-30938993589b.png)

The course which should end before 9:00pm but after 8:00pm

![image](https://user-images.githubusercontent.com/49500055/126845387-0469e3b8-869c-445b-b1ce-ac13aab26438.png)

The course with a lab that should end after 9:00pm

![image](https://user-images.githubusercontent.com/49500055/126845437-6fa6443f-7c5d-4e05-b8a1-d8911531c891.png)

#### Desktop info:
 - OS: Windows 10 21H1 Build 19043.1110
 - Browser: Firefox, V90.0.2

**Comment by aomi** [comment]
Thanks for the report. This isn't too tricky to fix so we'll likely fix this soon.

@JoshoTheMosho I think in terms of a implementation, we stick with that we have right **but** if there's courses that go beyond the max time, we extend it to fit (if it ends at 9:20pm we extend to 9:30pm to 10pm etc.). I think we can also add this logic to work for weekend events too (if there's anything that lands on a weekend, we add that day to the calendar)
