### ISSUE TITLE
Add social media integration to timetable sharing

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/courseup#260]
See mock-ups in the POST flow for where social media integrations will be on [figma](https://www.figma.com/file/Lvep4lP1867IZUiVQHUtaz/CourseUp?node-id=515%3A10672)

For this ticket, we will need to scope out which media platforms we want to use and explore their APIs to see if it is doable.
Feel free to add to this list:

- Facebook (messenger)
- WhatsApp
- Telegram
- Discord

**Comment by szeckirjr** [comment]
Could we use something like [react-share](https://github.com/nygardk/react-share) instead of implementing each of their APIs separately?

**Comment by keithradford** [comment]
Good call @szeckirjr , I wasn't aware of it. Looks super simple to use

**Comment by szeckirjr** [comment]
Great @keithradford! In that case, I can work on this as well as it'd be pretty simple adding those to the POST flow I'm working on already 😄
