### ISSUE TITLE
Clean-up z-index use

### ISSUE THREAD

**Issue by szeckirjr** [VikeLabs/courseup#262]
**Describe the Bug/Issue**

Currently, the header/banner z-index is set to 1000. This messes up with certain Chakra components (like modals, as they will be partly covered).

Chakra [recommends not exceeding z-index values of more than 1 or 2](https://chakra-ui.com/guides/z-index).

**Screenshots**
![image](https://user-images.githubusercontent.com/50898635/128651156-6509ceed-60a2-4d9f-89c3-fd879678ae21.png)

**Comment by Schorcher5** [comment]
I think this issue has already been resolved. I attempted to recreate this issue with now success. The z index of the header/banner looks to be set to auto, not 1000

**Comment by keithradford** [comment]
@Schorcher5 This probably got cleaned up at some point in another PR. Thanks for pointing it out!
