### ISSUE TITLE
Bug: Course `More Information` button resets week view to current week

### ISSUE THREAD

**Issue by MNThomson** [VikeLabs/courseup#279]
**Describe the Bug/Issue**
When a user clicks on the `More Information` button in the `Saved Courses` sidebar, the week viewed is reset to the current week.

**To Reproduce**
Steps to reproduce the bug:
1. Add a course to your CourseUp schedule
2. Change the week viewed
3. Click on the `More Information` button
4. Observe the week has been reset to the current week

**Expected Behaviour**
When expanding to gain more information on a course/sections, the currently viewed week should not be reset.

**Screenshots**
Added course and looking at a date in the future:
![image](https://user-images.githubusercontent.com/73045936/132252760-eafef08c-d3b2-4a62-84ea-50f609782730.png)
Clicked on the course `More Information` button and is back to present day:
![image](https://user-images.githubusercontent.com/73045936/132252830-91f2ad52-2ec6-483f-9788-7f565786a368.png)

**Desktop/Mobile**

 - OS: Windows 10
 - Browser: Firefox
 - Version: 91.0.2

**Comment by logankuzyk** [comment]
Assign me please!
