### ISSUE TITLE
Create Page component

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/courseup#312]
We have a growing amount of different pages on CourseUp, and since we consistently have the header, feedback button, and sometimes sidebar it can be tedious to fill in the rest of the page with the actual content.

It would be beneficial if we had a `Page` component that the highest level of each page could be wrapped in so this formatting logic didn't have to be repeated, would minimize error and make refactors easy, as well as make new page creation easier in general.

For example [this chunk](https://github.com/VikeLabs/courseup/blob/main/src/pages/registration/containers/RegistrationContainer.tsx#L22-L28) of components on the registration page would be a single `Page` component.

- [ ] Find all instances of a page in our codebase
- [ ] Create consistent wrapper component (`Page` component) in our common folder
- [ ] Replace all pages with this component

**Comment by richardsaseun14** [comment]
Hello @keithradford. Can i have this one?
