### ISSUE TITLE
Logo contest

### ISSUE THREAD

**Issue by aomi** [VikeLabs/courseup#329]
A logo contest for CourseUp.
https://courseup.vikelabs.ca/contest?from=github

**Comment by aomi** [comment]
@richardsaseun14 hey!
It is! I've updated the description to reference the details of the contest. If you're a University of Victoria student or alumni you are free to enter!

**Comment by richardsaseun14** [comment]
@aomi i am not a student of university of Victoria.

**Comment by jensengillett** [comment]
You might want to remove the submission countdown from the main page since submission entries are closed - at the moment it's just a big thing saying '0'
![image](https://user-images.githubusercontent.com/62229586/160962805-f577cbdb-455d-4618-9a60-c928d0fcfa34.png)
