### ISSUE TITLE
Bug: Failed to execute 'removeChild' on 'Node' after clicking on a summer 2022 course

### ISSUE THREAD

**Issue by klemie** [VikeLabs/courseup#335]
**Describe the Bug/Issue**
When first loading in > search course from the 2022 summer term > click the course: after 20 seconds your screen will display 'An error has occurred' and the debugger will give the error `DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`. Refreshing does not seem to fix the problem. 

**To Reproduce**

Steps to reproduce the behaviour/bug/issue:
1. Fresh load into the page (fresh search)
2. Set term to Summer 2022
3. Search for a course (I did any ECE)
4. Double check that the term is set to summer 2022
5. After a couple seconds the error will occur 

**Expected Behaviour**
Not to get an error when checking my courses lol. 

To see the course details for more than 5 seconds. 

**Screenshots**
![image](https://user-images.githubusercontent.com/45109638/155228847-9abd26e4-3243-4a55-84db-93c0690e12e0.png)
![image](https://user-images.githubusercontent.com/45109638/155228884-6fb7ef55-2e94-4ded-b738-95258cc808b5.png)

**Desktop/Mobile**

 - OS: Windows 10 (64-bit)
 - Browser: Chrome
 - Version: 98.0.4758.102 

**Additional Context**
N/a

**Comment by aomi** [comment]
Going to close after investigating the issue with the reporter and concluding it is likely a browser extension interfering with some browser APIs.
