### ISSUE TITLE
Bug: Term select does not stay for summer 2022 

### ISSUE THREAD

**Issue by klemie** [VikeLabs/courseup#336]
**Describe the Bug/Issue**

Selecting summer 2022 term in term drop down on main page. After Searching and selecting the course the term resets to spring 2022.

**To Reproduce**

Steps to reproduce the behaviour/bug/issue:

1. On main page change drop down to summer 2022
2. search and click on a course
3. term get reset to spring 2022

**Expected Behaviour**

For the drop to stay on Summer 2022

**Screenshots**
Step 1:
![image](https://user-images.githubusercontent.com/45109638/155229870-d1a436fc-f116-4302-84f4-3c81a9eab044.png)
Step 2:
![image](https://user-images.githubusercontent.com/45109638/155229958-58247584-2f84-4c2a-afd1-30af0cb6966a.png)
Step 3:
![image](https://user-images.githubusercontent.com/45109638/155229988-73c7189f-1a93-47c6-a7af-0c7da58ab8ce.png)

**Desktop/Mobile**

 - OS: windows 10
 - Browser: Chrome
 - Version: 98.0.4758.102

**Additional Context**

**Comment by aomi** [comment]
I was able to reproduce this. Weirdly this doesn't happen when looking on the fall semester.
