### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by Russell-Waterhouse** [VikeLabs/courseup#353]
I know open source maintainers never get appreciated for the work they do, so I just wanted to thank everyone that has contributed to this project. I just finished registering for summer courses, and this project made that so quick and simple! It even has dark mode! 

Thank you so much!

**Comment by aomi** [comment]
@Russell-Waterhouse Thanks for being the VP of Student Life! Wouldn't have this club or project without the help of ESS <3
