### ISSUE TITLE
Show "Additional Notes" in Timetable view

### ISSUE THREAD

**Issue by malcolmseyd** [VikeLabs/courseup#354]
As an engineering student, many of the courses that I register for have section restrictions. While creating my schedule with CourseUp, I find myself constantly tabbing between the Timetable view and the Calendar view in order to see which sections I am allowed to register in. It would be useful if I were able to stay on the Timetable view the entire time.

I figured that a good solution to this problem is to show "Additional Notes" on the Timetable view.

**Comment by malcolmseyd** [comment]
I plan on giving this issue a go, I'll keep this thread updated.

**Comment by aomi** [comment]
@malcolmseyd might not be "hover" but I think this would be a good starting point
https://chakra-ui.com/docs/components/overlay/popover
https://chakra-ui.com/docs/components/overlay/tooltip
