### ISSUE TITLE
Move term selector beside search bar

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/courseup#372]
As per feedback from users, the term selector probably makes more sense to be beside the search bar. It should be obvious to the user what term they are searching in and this moves it to a more viable spot.

- [ ] Edit mock-ups on figma to match this (let's make sure it looks good too and explore some options first)
- [ ] Make changes in frontend

![CourseUp Feedback - Truman Gao](https://user-images.githubusercontent.com/53020925/167489343-9aec0c08-0118-4045-993f-b9c82ec8ce8b.png)
Image from feedback form

**Comment by szeckirjr** [comment]
@liamshatzel have you looked into this? I might be able to put some Figma examples up if it'd help!

**Comment by liamshatzel** [comment]
@szeckirjr I think I had some figma mocks at some point but I got stuck on conditionally styling the dropdown. I can look into it again though
