### ISSUE TITLE
Feature Request: Detailed Calendar (Description) Export

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#385]
## Feature Request

As a student I want to have a detailed description within my `.ics` calendar export.

Explanation: I use my calendar app as a central information point and I find it helpful to have the instructors information within the calendar event and if any the zoom link for easy access each lecture (Link added manually after acquiring zoom link).

### Current `.ics`

```ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//courseup//courseup.vikelabs.ca//EN
BEGIN:VEVENT
UID:202209_CSC_370_A01_MR_
DTSTAMP;TZID=America/Vancouver:20220908T130000
DTSTART;TZID=America/Vancouver:20220908T130000
DTEND;TZID=America/Vancouver:20220908T142000
DESCRIPTION:CSC 370 A01
LOCATION:Engineering Comp Science Bldg 125
SUMMARY:CSC 370 A01
RRULE:FREQ=WEEKLY;BYDAY=MO,TH;UNTIL=20221205T142000
END:VEVENT
```

### Proposed `.ics`

```ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//courseup//courseup.vikelabs.ca//EN
X-WR-CALNAME:TERM Session: MONTH - MONTH YEAR
BEGIN:VEVENT
UID:CRN-YEAR-MONTH-SECTION@uvic.ca
DTSTAMP;VALUE=DATE-TIME:XXXXXXXXTXXXXXXZ
DTSTART;TZID=America/Vancouver;VALUE=DATE-TIME:XXXXXXXXTXXXXXX
DTEND;TZID=America/Vancouver;VALUE=DATE-TIME:XXXXXXXXTXXXXXX
DESCRIPTION:Title: Course Title\nInstructor: FirstName LastName\nSection: XXX\nCRN: XXXXX\nContact Information: EMAIL\nZoom Meeting: LINK
LOCATION:LOCATION
SUMMARY:COURSE XXX SECTION - TYPE
RRULE:FREQ=FREQUENCY;BYDAY=DAY;UNTIL=XXXXXXXXTXXXXXX;INTERVAL=X
END:VEVENT
END:VCALENDAR
```

---

This is a feature that I had implemented within my own (now outdated) python script for calendar export. You can see the implementation here: https://github.com/FlyteWizard/UVicSchedule.

I'm not sure if it is still possible with the new Banner system, but if it is I would find it extremely helpful.

<img width="250" alt="Example Calendar Event" src="https://user-images.githubusercontent.com/10472448/169705846-cac5f093-d0a6-4ca9-93f2-69f656b9f3c4.png">

**Comment by aomi** [comment]
@FlyteWizard The new UVic system (aka. Banner 9) does support ICS export. Have you seen if the format meets your needs?
If it doesn't, this feature would be a welcome addition given it doesn't modify much and only adds more useful information.

**Comment by FlyteWizard** [comment]
I didn't know they had an export feature 👀 

```ics
BEGIN:VEVENT
DTSTAMP:20220522T163740Z
DTSTART;TZID=America/Vancouver:20220504T163000
DTEND;TZID=America/Vancouver:20220504T175000
SUMMARY:Database Systems CSC 370 A01
RRULE:FREQ=WEEKLY;UNTIL=20220729T225900;BYDAY=MO,WE
TZID:America/Vancouver
UID:20220522T163740Z-Ellucian
LOCATION:Campus: Main Building: David Strong Building Room: C103 
DESCRIPTION:CRN: 30225\nCredit Units: 1.5\nLevel: Undergraduate\nInstructor: Sean Chester (Primary) \n
END:VEVENT
END:VCALENDAR
```

So it has some of the information, but is missing instructors contact information. Might still be worth it to implement (you can get the instructor contact information by clicking the instructors name), but as low priority.
