### ISSUE TITLE
Bug: Return `&` instead of `&amp;` in backend

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/courseup#395]
**Describe the Bug/Issue**

**To Reproduce**

Steps to reproduce the behaviour/bug/issue:

1. Go to any course that has a location with & (https://courseup.vikelabs.ca/calendar/202205/CSC?pid=Bk_cy_a7V)
1. scroll to location

**Expected Behaviour**

Should say `&` instead of `&amp;`

**Screenshots**

![image](https://user-images.githubusercontent.com/53020925/172684955-77991cad-4ae9-4d89-8a87-8a3b8492aecb.png)

**Comment by Schorcher5** [comment]
My first guess(without exploring the code fully) would be that there is some sort of encoding issue with html. If its alright with you, could I take a try and solve this issue?
