### ISSUE TITLE
Bug: Timetable uses incorrect time when in different time zone

### ISSUE THREAD

**Issue by Jasper-Nelligan** [VikeLabs/courseup#399]
**Describe the Bug/Issue**
The timetable is currently displaying the wrong time for each class for me. For example, CSC 375 starts at 8:30 am but on my timetable it's showing it starts at 9:30 (see screenshot). I assume this is because I'm in Calgary and so the hour is always one ahead.

Not too much of an issue since all courses are offset by the same amount, but for more extreme time zone differences this may look strange.

**To Reproduce**

Steps to reproduce the behaviour/bug/issue:

1. Register for CSC 375 for Fall 2022 in a different time zone (might be able to simulate this)

**Expected Behaviour**

CSC 375 should be displayed as starting at 8:30, not 9:30

**Screenshots**

![courseup_bug](https://user-images.githubusercontent.com/57274383/174723550-d10b3878-89fe-4a53-8177-d2ee5bf07d02.png)

**Desktop/Mobile**

 - OS: Windows 8
 - Browser: Brave

**Comment by Jasper-Nelligan** [comment]
Closing this since I didn't realize #393 was already filed

**Comment by aomi** [comment]
The issue you referenced is an issue when an event spans different time zones. This issue is related to an overall issue with handling of time locale.
