### ISSUE TITLE
Bug: Timetable Screenshots

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#402]
**Describe the Bug/Issue**

The following are bugs that sometimes appears when taking a screenshot.

1. Double Footer in Screenshot
2. Squished Room Numbers in Screenshot
3. Extra Padding Timetable Header in Screenshot
4. Colours Washed Out in Screenshot

**To Reproduce**

1. Unknown
2. Unknwon
3. Chromium Based (?) Bug. Go to timetable, navigate away, return and take a screenshot.
4. The colours appear washed out during screenshots. 

**Expected Behaviour**

1. The footer does not duplicate.
2. The room numbers remain visible within the event timeframe.
3. The extra padding doesn't appear in the screenshot.
4. The colours to remain true to the application.

**Screenshots**

1. 
![Issue 1](https://user-images.githubusercontent.com/10472448/175756425-4fecc4c7-afba-4468-adef-41125a73746a.png)

2. 
![Issue 2](https://user-images.githubusercontent.com/10472448/175756465-aba9f494-83d0-4a6f-94ed-d9d2867c21fd.png)

3. 
![Issue 3](https://user-images.githubusercontent.com/10472448/175756491-7fe57999-d2f0-4c2f-b9b2-5ac1a631254d.png)

4. 
![Issue 4](https://user-images.githubusercontent.com/10472448/175756538-a2293398-f054-479e-a688-41ea56f30889.png)

**Additional Context**

![Context for Issue 3](https://user-images.githubusercontent.com/10472448/175756574-b1f2874a-8bec-46a4-b447-abd4e514fadd.png)

Thank you @jensengillett for exploring issue 3.

---

### Additional Notes

- Feature Request: Copy to clipboard automatically.
- Issue: More spacing between bullet points on Registration page. (#406)

**Comment by jensengillett** [comment]
To put a little more info here on issue 3 - I could only manage to get it to happen on Chrome, but it consistently happened even in incognito and in both themes. Firefox and Edge (strangely enough, because it's chromium based) were both unaffected. Testing was done on Win10 at 100% scaling @ 1080p (no hiDPI).
