### ISSUE TITLE
Bug: Responsive Design - Registration Page

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#407]
**Describe the Bug/Issue**

Currently the registration page (and maybe others) are not responsive. The page breaks when resizing the screen.

**To Reproduce**

Steps to reproduce the behaviour/bug/issue:

1. Go to the registration page.
2. Resize the browser.

**Expected Behaviour**

I expect to be able to resize the browser without visual bugs being present.

**Screenshots**

https://user-images.githubusercontent.com/10472448/179373011-ec2b9340-4657-4b00-8587-197a51ab1547.mov

https://user-images.githubusercontent.com/10472448/179373029-455e50a0-5b19-438e-bbc3-fa6e4d81e639.mov

https://user-images.githubusercontent.com/10472448/179373039-73bd54d7-6c89-4cb1-bafd-34fdbbc63e6e.mov

**Desktop/Mobile**

- OS: macOS
- Browser: Safari (but can be observed in Microsoft Edge, Firefox, and Chrome)
- Version: Latest (July 16th 2022)

**Additional Context**

This is slightly related to the newest swiper feature, **however**, this has been an issue in various ways beforehand.

I'm not sure there is a quick fix, but trying to make the site responsive and removing the restrictions on overflow and widths might be a goal for the future.

**Comment by szeckirjr** [comment]
I just pushed a [commit](https://github.com/VikeLabs/courseup/pull/405/commits/e9aa958f691b26e88dc780386575598f4c607d1f) that should fix it in my mobile-bugs branch (PR open [here](https://github.com/VikeLabs/courseup/pull/405))!! This was a problem with any page that did not have any sidebars. Thankfully it was an easy fix :)
