### ISSUE TITLE
feat: Select Multiple Tutorials / Labs (Possibly Lectures) Sections

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#424]
As a student and teaching assistant I want to be able to select multiple tutorial/lab sections.

**Reasoning**: I want to be able to schedule and plan my semester around the courses that I assist in teaching. 

**Proposal**: An "advanced" course planning and scheduling option to enable multiple selection. I think an option select to toggle "advanced" settings will reduce the confusion of students who need only to select a single tutorial/lab section.

<img width="1792" alt="courseup multiple tutorials selected" src="https://user-images.githubusercontent.com/10472448/203661465-3062ec7e-6175-4dca-9ec4-c7afb3d58211.png">

**Comment by keithradford** [comment]
This is also possible for a subset of courses: https://github.com/VikeLabs/courseup/issues/233
