### ISSUE TITLE
feat: Add Schedule Unique Identifier to Screenshot File Name

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#470]
As a student I want to be able to take screenshots of multiple schedules without having to manually modify the file name for each different schedule.

**Reasoning**:

- I have schedule A and schedule B.
- I screenshot schedule A as `202305_calendar.png` (i.e., default file name).
- I then screenshot schedule B, but I need to manually edit the file name to `202305_calendar_b.png` (the default file name is increment to `202305_calendar-2.png` by default on OS).

**Proposal**: Add the schedule unique identifier (i.e., `httos://courseup.vikelabs.ca/s/nsmChzvmCYaD`) to the file name. OR Add the courses of the schedule to the file name.

Example: `202305_calendar_nsmChzvmCYaD.png` OR `202305_calendar_csc423a02_csc260a02_math202a01_math202t03.png`. 

**Notes**: The feature can be classified as a `Good First Issue`.

**Comment by szeckirjr** [comment]
It would be cool to have a default value with an option to save the name before downloading too 
quick figma sketch:
<img width="891" alt="image" src="https://github.com/VikeLabs/courseup/assets/50898635/3669f528-4f6d-4b48-b8b4-88db8b35fcd0">
