### ISSUE TITLE
Bug: Uses "Winter 2023" instead of "Fall 2023"

### ISSUE THREAD

**Issue by Jasper-Nelligan** [VikeLabs/courseup#475]
**Describe the Bug/Issue**
The blue notification at the top says "The Winter 2023 calendar is now available. Happy scheduling!" but it should say "Fall 2023" because that's what the dropdown menu for selecting a term uses.

**Screenshots**
![Screenshot (41)](https://github.com/VikeLabs/courseup/assets/57274383/492ae6f2-c27a-4326-96f2-0fd6415dec12)

 - OS: Windows 8
 - Browser: Brave

**Comment by szeckirjr** [comment]
Hey! I think we're just following [UVic's nomenclature](https://www.uvic.ca/calendar/dates/#:~:text=Monday%2C%20August%2021st-,Winter%20session%20%2D%20first%20term,-September%202023)

Technically we're divided into two "sessions", Summer and Winter (which includes Fall and Spring). So when we say `Winter 2023` calendar is available, we mean Fall and Spring terms, so it just takes you to the first one 🤷‍♂️ 

I think this might be a case of _it's not a bug, it's a feature_, but let me know what you think

**Comment by Jasper-Nelligan** [comment]
Ah okay. I never realized Uvic used that nomenclature in that way.  I wonder if it would be less confusing to say "Fall 2023 and Winter 2024 calendars are now available". Or, could it be "Winter 2023-2024 calendar is now available" to show the year change? Because when I see Winter 2023 I think of the semester that's already passed. Just my thoughts.

And yes I can update this to be a feature which seems more appropriate

**Comment by szeckirjr** [comment]
Ah that's a really good point! "Winter 2023-24 calendar is now available!" might work too, I just don't want it to get too long but I see where the confusion comes from. I'll bring it up in the CourseUp meeting this week and we'll push a change to it (which you're welcome to do too if you want)

And about the feature, sorry, I didn't mean the actual issue, I think this is labeled great! It just felt like one of those dev cases of "I promise this is not a bug and it's exactly how I intended this to work" hahaha

<img width="350px" src="https://github.com/VikeLabs/courseup/assets/50898635/739a7ddf-b071-44b9-9bf7-6c6833ff7945" />

**Comment by Jasper-Nelligan** [comment]
Ah gotcha. Yeah let me know what wording you end up going with because I wouldn't mind contributing!
