### ISSUE TITLE
Bug: Spring 2024 classes not showing under "Explore courses"

### ISSUE THREAD

**Issue by RyanBarclay** [VikeLabs/courseup#499]
**Describe the Bug/Issue**
No classes showing up under Explore Courses with the following params:

* spring 2024
* toggle only show courses in session on

Not inline with calendar or class look up data.
ex: [example](https://courseup.vikelabs.ca/calendar/202401/ADMN)

**To Reproduce**

Steps to reproduce the behaviour/bug/issue:

1. [Go to course up](https://courseup.vikelabs.ca/)
1. Select Spring 2024 on menu selector
1. Select Explore courses
1. Hit CSC, and see no classes present

**Expected Behaviour**
Should be filled with classes in spring

**Screenshots**
![Screenshot 2023-08-15 at 5 46 10 PM](https://github.com/VikeLabs/courseup/assets/43585909/ad1ae979-3524-40a0-951e-03af244e23ab)

**Desktop/Mobile**

 - OS: Mac OS Ventura 13.5 (M2)
 - Browser: Arc (just a chromium browser for mac)
 - Version 1.3.0 (40706)
 -Chromium Engine Version 115.0.5790.170

**Comment by szeckirjr** [comment]
thank you for the feedback! sorry about the inconvenience in the meantime

closing this as it is a duplicate to #478
