### ISSUE TITLE
Improve and expand on section badges 

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/courseup#55]
![firefox_Q7hQTLYdLQ.png](https://images.zenhubusercontent.com/5f973f7c87cad5309bf82827/5f1ab3f3-8564-4b1b-bc9b-d2f8a1f5df49)

Currently course sections display badges based on a few criteria such as `online`, `asynchronous`, and `SENG/CSC only` (see screenshot). However, the code is somewhat hacky and could be improved on by being made more generic and reliable, as well as hit more cases than the current ones.

For this ticket, you could take a look at the current implementation and think of ways it can be improved on and look through subjects other than SENG that have generic attributes which could be represented as a badge. Badges are key information we want to show users front and center, so consider this when looking. 
An example of why we should refactor the code would be that there is not a `synchronous` badge because using the current logic, `synchronous` would be found when `asynchronous` is present and you can see how that's wrong.

**Comment by JoshoTheMosho** [comment]
I'd like to take on this issue as an ongoing thing to work on and better familiarize myself with everything 

# First change
Added on a 'Synchronous' tag to courses that were online but not asynchronous, kept it off of face-to-face courses to avoid clutter

# Before
![image](https://user-images.githubusercontent.com/48394084/125596705-e1104274-becd-4faf-afe9-875a75644858.png)

# After
![image](https://user-images.githubusercontent.com/48394084/125596835-6c17d644-65fa-4a29-9b61-830640cbe99e.png)

**Comment by JoshoTheMosho** [comment]
ECE 216 and ECE 220 can be mapped out
